<a href="https://colab.research.google.com/github/DikshaDayal/Machine-Learning-part-02-/blob/main/5.3.%20Working_with_Matrix_in_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Import the Dependencies
import numpy as np

In [8]:
#Creating a matrix using numpy
matrix_1 = np.array(([1,2],[3,4]))
print(matrix_1)

[[1 2]
 [3 4]]


In [9]:
#Dimensions of A Matrix
matrix_1.shape

(2, 2)

In [10]:
matrix_2 = np.array([[10,35,45],[50,64,80],[20,15,90]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [11]:
matrix_2.shape

(3, 3)

Creating Matrix with random Values

In [12]:
matrix_3 = np.random.rand(3,3)
print(matrix_3)
matrix_3.shape

[[0.80801674 0.06362119 0.05597212]
 [0.79702565 0.05199995 0.99613521]
 [0.08673015 0.005531   0.20207743]]


(3, 3)

In [14]:
matrix_4 = np.random.randint(10,100 , (4,4))
print(matrix_4)
matrix_4.shape

[[80 94 65 95]
 [81 20 70 38]
 [61 56 34 16]
 [94 87 47 60]]


(4, 4)

**Matrix with all the values as 1**

---



In [18]:
matrix_5 = np.ones(shape = (4,4) , dtype=int)
print(matrix_5)
matrix_5.shape

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


(4, 4)

**Null Matrix**

---



In [21]:
matrix_5 = np.zeros(shape = (4,4) , dtype=int)
print(matrix_5)
matrix_5.shape

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


(4, 4)

**Identity Matrix**

---



In [22]:
matrix_6 = np.eye(4 , dtype=int)
print(matrix_6)
matrix_6.shape

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


(4, 4)

**Transpose of an Matrix**

---



In [24]:
matrix_7 = np.random.randint(0 ,5 , size = (3,3) , dtype=int)
print(matrix_7)
matrix_7.shape

[[1 3 3]
 [3 4 1]
 [2 4 1]]


(3, 3)

In [25]:
print("Transpose Of the Matrix_7 is :- ")
print(matrix_7.transpose())

Transpose Of the Matrix_7 is :- 
[[1 3 2]
 [3 4 4]
 [3 1 1]]
