<a href="https://colab.research.google.com/github/DikshaDayal/Machine-Learning-part-02-/blob/main/5.4.%20Operations_On_Matrix_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importing Libraries and Dependencies
import numpy as np

**Matrix Addition**

In [6]:
A = np.array(([1,2],[3,4]))
B = np.array(([1,2],[3,4]))
print(A)
print('Dimensions of the matrix :- ' , A.shape)
print(B)
print('Dimensions of the matrix :- ' , B.shape)

print(A+B)

[[1 2]
 [3 4]]
Dimensions of the matrix :-  (2, 2)
[[1 2]
 [3 4]]
Dimensions of the matrix :-  (2, 2)
[[2 4]
 [6 8]]


In [12]:
Sum = np.add(A,B)
print('The Sum Of A and B is :- ')
print(Sum)

The Sum Of A and B is :- 
[[2 4]
 [6 8]]


In [10]:
# create two matrices with random values
C = np.random.randint(10,50, (3,3))
D = np.random.randint(20,50,(3,3))
print('The Matrix of C is :- ')
print(C)
print('The Matrix of D is :- ')
print(D)
print('The Sum of C and D is :- ')
print(C+D)

The Matrix of C is :- 
[[47 17 29]
 [33 24 41]
 [34 35 34]]
The Matrix of D is :- 
[[41 45 22]
 [41 29 49]
 [47 31 23]]
The Sum of C and D is :- 
[[88 62 51]
 [74 53 90]
 [81 66 57]]



Matrix Subtraction

---



In [13]:
A = np.array(([1,2],[3,4]))
B = np.array(([1,2],[3,4]))
print(A)
print('Dimensions of the matrix :- ' , A.shape)
print(B)
print('Dimensions of the matrix :- ' , B.shape)

print(A-B)

[[1 2]
 [3 4]]
Dimensions of the matrix :-  (2, 2)
[[1 2]
 [3 4]]
Dimensions of the matrix :-  (2, 2)
[[0 0]
 [0 0]]


In [14]:
Difference = np.add(A,B)
print('The Difference Of A and B is :- ')
print(Difference)


The Difference Of A and B is :- 
[[2 4]
 [6 8]]


In [15]:
# create two matrices with random values
C = np.random.randint(10,50, (3,3))
D = np.random.randint(20,50,(3,3))
print('The Matrix of C is :- ')
print(C)
print('The Matrix of D is :- ')
print(D)
print('The Difference of C and D is :- ')
print(C-D)

The Matrix of C is :- 
[[13 37 14]
 [43 23 23]
 [24 49 36]]
The Matrix of D is :- 
[[48 40 43]
 [27 25 31]
 [42 41 41]]
The Difference of C and D is :- 
[[-35  -3 -29]
 [ 16  -2  -8]
 [-18   8  -5]]


**Multiplying a matrix by a scalar**

In [17]:
A = np.random.randint(10,20 , (3,3))
print('The Matrix A is :- ',A)

The Matrix A is :-  [[11 12 18]
 [16 12 12]
 [17 19 19]]


In [21]:
mul = 5
print('The Matrix after multiplying with' , mul , 'is :-' )
print(np.multiply(mul,A))

The Matrix after multiplying with 5 is :-
[[55 60 90]
 [80 60 60]
 [85 95 95]]


**Multiplying 2 Matrices**

---



In [30]:
A = np.random.randint(10,20 , (3,3))
B = np.random.randint(10,20 , (3,3))
print('The Matrix A is :- ')
print(A)
print('The Matrix B is :- ')
print(B)
# Element wise Multiplication
# print('Multiplyng Matrix A and B :- ')
# print(np.multiply(A,B))

The Matrix A is :- 
[[11 13 10]
 [14 17 11]
 [10 14 16]]
The Matrix B is :- 
[[13 19 18]
 [16 14 12]
 [18 11 18]]


**Dot product**

---



In [28]:
dot_product = np.dot(A,B)
print('Dot product of A and b Matrix is :- ')
print(dot_product)
print ('Dimensions of the resultant matrix :- ')
dot_product.shape

Dot product of A and b Matrix is :- 
[[550 600 400]
 [619 710 450]
 [598 688 440]]
Dimensions of the resultant matrix :- 


(3, 3)

**Cross Product**

---



In [27]:
cross_product = np.cross(A,B)
print(cross_product)
print ('Dimensions of the resultant matrix :- ')
cross_product.shape

[[-142   66   44]
 [ -17   17    0]
 [   6  -14    9]]
Dimensions of the resultant matrix :- 


(3, 3)

Multiplying Two Matrices Elements wise


---



In [29]:
print(np.multiply(A,B))

[[121 221 160]
 [289 289 110]
 [221 180 120]]
